import { createSlice, PayloadAction } from '@reduxjs/toolkit';

// Define the type for the user state
interface UserState {
  _id?: string;
  userId?: string;
  account_id?: string;
  party_id?: string;
  profile_name?: string;
  phonenumber?: string;
  role?: string;
  permissions?: string[];
  date?: string;
  status?: string;
  mfaEnabled?: boolean;
  __v?: number;
}

interface InitialStateProps {
    user: UserState | null;
    refreshToken: string | null;
    accessToken: string | null;
}

const initialState: InitialStateProps = {
    user: null,
    refreshToken: null,
    accessToken: null,
};

// Create a slice for user management
const userSlice = createSlice({
    name: 'user',
    initialState,
    reducers: {
        setUser(state, action: PayloadAction<UserState>) {
            state.user = action.payload;
        },
        clearUser(state) {
            state.user = null;
        },
        setToken(state, action: PayloadAction<string | null>) {
            state.accessToken = action.payload;
        },
        clearToken(state) {
            state.accessToken = null;
        },
        setRefreshToken(state, action: PayloadAction<string | null>) {
            state.refreshToken = action.payload;
        },
        logout(state) {
            state.user = null;
            state.accessToken = null;
            state.refreshToken = null;
            localStorage.removeItem('refreshToken');
        },
    },
});

// Export actions generated by the slice
export const { setUser, clearUser, setToken, clearToken, setRefreshToken, logout } = userSlice.actions;

// Export the reducer
export default userSlice.reducer;
